# Generated by Django 3.2.5 on 2021-07-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='type',
            new_name='slider_types',
        ),
    ]
