# Generated by Django 3.2.5 on 2021-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_slider_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slider_types',
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/slider'),
        ),
    ]
