# Generated by Django 3.2.5 on 2021-07-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210708_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='background_image',
            field=models.ImageField(default=1, upload_to='images/slider'),
            preserve_default=False,
        ),
    ]
