# Generated by Django 3.2.5 on 2021-07-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_slider_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/slider'),
        ),
    ]
