# Generated by Django 3.2.5 on 2021-07-09 11:29

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_slider_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='background_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/slider'),
        ),
    ]
