# Generated by Django 3.2.5 on 2021-07-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_brand_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
