# Generated by Django 3.2.5 on 2021-07-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
