# Generated by Django 3.2.5 on 2021-07-14 06:48

from django.db import migrations, models
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0003_delete_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('photo', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/vendors/', verbose_name='Photo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
