# Generated by Django 3.2.5 on 2021-07-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
    ]
