# Generated by Django 3.2.5 on 2021-07-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_photo'),
        ('sales', '0004_alter_saleitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(default='', limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
    ]
