# Generated by Django 3.2.5 on 2021-07-15 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_saleitem_is_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.sale'),
        ),
    ]
