# Generated by Django 3.2.5 on 2021-07-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_sale_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='slug',
        ),
    ]
