# Generated by Django 3.2.5 on 2021-07-08 05:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='information',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
