# Generated by Django 3.2.5 on 2021-07-09 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_brand_brand_name'),
        ('products', '0005_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='703a392e-3694-4ff3-8521-2bb97d85f777', on_delete=django.db.models.deletion.CASCADE, to='main.brand'),
            preserve_default=False,
        ),
    ]
