# Generated by Django 3.2.5 on 2021-07-09 11:29

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/matrials/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/reviews/'),
        ),
    ]
