# Generated by Django 3.2.5 on 2021-07-12 05:51

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210709_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=products.models.generate_id, max_length=128, unique=True),
        ),
    ]
